version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapassword
      POSTGRES_DB: myapp
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres: